### PR TITLE
Set the correct value of aria-selected attribute for not selected items.

### LINKED ISSUE #102: All tabs are always announced as selected, even when they're not.
### Description

paper-tabs always are being announced as selected. I used ChromeOS (67.0.3396.99) and ChromeVox screen reader.

### Expected outcome
Only selected tab should be announced as selected.

### Actual outcome
All are announced as selected

### Steps to reproduce

Go to https://www.webcomponents.org/element/PolymerElements/paper-tabs enable screen reader and switch between the tabs.

### Browsers Affected

- [x] Chrome
- [?] Firefox
- [?] Safari 9
- [?] Safari 8
- [?] Safari 7
- [?] Edge
- [?] IE 11
- [?] IE 10

### PR DESCRIPTION
**Pull request by simon600**
Fixes #102.

### CODE REVIEW

File: iron-menu-behavior.js [hunk 1]
```diff
@@ -138,6 +139,7 @@ export const IronMenuBehaviorImpl = {
 
     this.items.forEach(function(item) {
       item.setAttribute('tabindex', item === selectedItem ? '0' : '-1');
+      this._applySelection(item, item === selectedItem);
```
Comment (bicknellr) [inline iron-menu-behavior.js]: `IronSelectableBehavior._applySelection`, which `this._applySelection` calls into, will dispatch an `iron-select` and `iron-deselect` event for the given item. So, I think this means that doing this in `_resetTabindices` will dispatch events for all items, which I'm not sure we want to do since that happens every time items change or the element is attached. Maybe directly setting `aria-selected` here is more appropriate? WDYT?

Comment (simon600) [reply iron-menu-behavior.js]: Yeah, you're right. I changed the code to directly set aria-selected in _resetTabindices instead.

File: iron-menu-behavior.js [hunk 2]
```diff
@@ -138,6 +139,8 @@ export const IronMenuBehaviorImpl = {
 
     this.items.forEach(function(item) {
       item.setAttribute('tabindex', item === selectedItem ? '0' : '-1');
+      item.setAttribute(
+          'aria-selected', item === selectedItem ? 'true' : 'false');
```
Comment (bicknellr) [inline iron-menu-behavior.js]: This looks like it will only set `aria-selected` to `true` for the first selected item if there's more than one. (`tabindex` intentionally behaves this way so that the menu only appears as one item in the sequential focus navigation order.)

**Review by bicknellr — CHANGES_REQUESTED** [review]

File: iron-menu-behavior.js (hunk 2 above)
Comment (simon600) [reply iron-menu-behavior.js]: Good point. Changed it so that it's set on all selected items.

File: iron-menu-behavior.js [hunk 3]
```diff
@@ -125,11 +125,26 @@ export const IronMenuBehaviorImpl = {
...
   /**
    * Resets all tabindex attributes to the appropriate value based on the
    * current selection state. The appropriate value is `0` (focusable) for
    * the default selected item, and `-1` (not keyboard focusable) for all
-   * other items.
+   * other items. Also sets the correct initial values for aria-selected
+   * attribute, true for default selected item and false for others.
    */
   _resetTabindices: function() {
     var selectedItem = this.multi ?
```
Comment (bicknellr) [inline iron-menu-behavior.js]: Could you rename this to `firstSelectedItem`?

File: iron-menu-behavior.js [hunk 4]
```diff
@@ -138,6 +153,7 @@ export const IronMenuBehaviorImpl = {
 
     this.items.forEach(function(item) {
       item.setAttribute('tabindex', item === selectedItem ? '0' : '-1');
+      item.setAttribute('aria-selected', this._isSelected(item));
```
Comment (bicknellr) [inline iron-menu-behavior.js]: Would using `this._selection.isSelected(item)` work here, instead of introducing `_isSelected`? ([`this._selection`, an `IronSelection`, is inherited from `IronSelectableBehavior`](https://github.com/PolymerElements/iron-selector/blob/05322d496414fe3bbdcadc0aea2cd9d2bc06ba58/iron-selectable.js#L148); [`IronSelection#isSelected`](https://github.com/PolymerElements/iron-selector/blob/05322d496414fe3bbdcadc0aea2cd9d2bc06ba58/iron-selection.js#L47-L55))

Sorry, If I had noticed this yesterday I would have mentioned it in that comment.

File: iron-menu-behavior.js (hunk 3 above)
Comment (simon600) [reply iron-menu-behavior.js]: Sure. I also renamed it in one other place.

File: iron-menu-behavior.js (hunk 4 above)
Comment (simon600) [reply iron-menu-behavior.js]: Yeah, good idea.

**Review by bicknellr — APPROVED** [review]
Thanks!
